# SwiftLint Configuration for SwiftServe
# Documentation: https://realm.github.io/SwiftLint/

excluded:
  - .build
  - .swiftpm
  - Tests/LinuxMain.swift

# Rule Configuration
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

disabled_rules:
  - todo # Allow TODO comments during development

# Custom Rule Configuration
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ip
    - to
    - db
    - os

large_tuple:
  warning: 3
  error: 4

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 4

# Reporter Configuration
reporter: "xcode"

# Custom Rules
custom_rules:
  no_print_statements:
    name: "No Print Statements"
    regex: "print\\("
    message: "Use Logger instead of print statements"
    severity: warning
    
  no_force_cast:
    name: "No Force Casting"
    regex: "as!"
    message: "Avoid force casting, use safe casting instead"
    severity: error
    
  no_force_unwrap:
    name: "No Force Unwrapping"
    regex: "!\\s*$"
    message: "Avoid force unwrapping, use safe unwrapping instead"
    severity: warning