name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        swift-version: ['6.0']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install Dependencies and Swift (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        # Install dependencies including OpenSSL for TLS certificate generation
        sudo apt-get update
        sudo apt-get install -y curl openssl
        
        # Download and install Swift 6.0.1 directly
        cd /tmp
        curl -LO "https://download.swift.org/swift-6.0.1-release/ubuntu2204/swift-6.0.1-RELEASE/swift-6.0.1-RELEASE-ubuntu22.04.tar.gz"
        tar xzf swift-*.tar.gz
        sudo mv swift-*-RELEASE-ubuntu22.04 /usr/local/swift
        echo "/usr/local/swift/usr/bin" >> $GITHUB_PATH
        
    - name: Install Dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # Install OpenSSL for TLS certificate generation
        brew install openssl
        
    - name: Setup Xcode (macOS)
      if: matrix.os == 'macos-latest'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Verify Swift Installation
      run: |
        swift --version
        
    - name: Verify OpenSSL Installation
      run: |
        echo "Checking OpenSSL availability..."
        which openssl || (echo "OpenSSL not found in PATH" && exit 1)
        openssl version || (echo "OpenSSL version command failed" && exit 1)
        echo "OpenSSL is properly installed and functional"
        
    - name: Run Tests
      run: |
        if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          # Use xcodebuild for macOS to ensure proper XCTest framework linking
          swift package generate-xcodeproj
          xcodebuild test -scheme SwiftServe-Package -destination 'platform=macOS'
        else
          # Use swift test for Ubuntu
          swift test -v
        fi