name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        swift-version: ['5.9', '5.10']
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install Swift (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y curl
        
        # Download and install Swift
        if [[ "${{ matrix.swift-version }}" == "5.9" ]]; then
          SWIFT_URL="https://download.swift.org/swift-5.9.2-release/ubuntu2204/swift-5.9.2-RELEASE/swift-5.9.2-RELEASE-ubuntu22.04.tar.gz"
        else
          SWIFT_URL="https://download.swift.org/swift-5.10.1-release/ubuntu2204/swift-5.10.1-RELEASE/swift-5.10.1-RELEASE-ubuntu22.04.tar.gz"
        fi
        
        cd /tmp
        curl -LO $SWIFT_URL
        tar xzf swift-*.tar.gz
        sudo mv swift-*-RELEASE-ubuntu22.04 /usr/local/swift
        echo "/usr/local/swift/usr/bin" >> $GITHUB_PATH
        
    - name: Install Swift (macOS)
      if: matrix.os == 'macos-latest'
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}
        
    - name: Verify Swift Installation
      run: |
        swift --version
        swiftc --version
        
    - name: Run Tests
      run: swift test -v